version: 2
jobs:
  build:
    docker:
    - image: circleci/node:8.11.3
    working_directory: ~/investment-projects-prototype
    steps:
    - checkout
    - run: npm version
    - run: yarn --version
    - run: yarn cache clean
    - run: yarn install
    - run: yarn build:dist
    - run: yarn test
    - run:
        name: Deploy Master to Heroku
        command: |
          git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
