version: 2
jobs:
  build:
    docker:
    - image: circleci/node:10.13.0
    working_directory: ~/investment-projects-prototype
    steps:
    - checkout
    - run: yarn install
    - run: yarn test
    - run:
        name: Deploy Master to Heroku
        command: |
          git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
